CLIENT_ID="CLIENT ID FROM NEXTID MANAGEMENT"
CLIENT_SECRET="CLIENT SECRET FROM NEXTID MANAGEMENT"
CLIENT_SCOPES="CLIENT SCOPES SEPARATED BY SPACE"
NEXTID_DOMAIN="NEXTID DOMAIN URL f.e cloud.nextplatform.ai"
NEXTID_TENANT="NEXTID TENANT"

node server.js $CLIENT_ID $CLIENT_SECRET $CLIENT_SCOPES $NEXTID_DOMAIN $NEXTID_TENANT
